[colors.bright]
black = "0x585c6f"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xffffff"
yellow = "0xdeb974"

[colors.normal]
black = "0x363a4e"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.primary]
background = "0x2b2d3a"
foreground = "0xc5cdd9"

[font]
size = 11

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[terminal.shell]
args = ["new-session", "-A"]
program = "tmux"
